spring.sendgrid.api-key:  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
spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
